kind: Deployment
apiVersion: apps/v1
metadata:
   name: mydevops
spec:
   replicas: 2
   selector:      # tells the controller which pods to watch/belong to
    matchLabels:
     app: mydevops
   template:
      metadata:
        labels:
          app: mydevops
      spec:
       containers:
        - name: mydevops
          image: DevOpsPrj/pipeline-demo
          imagePullPolicy: Always
          ports:
          - containerPort: 80
