kind: Service                             
apiVersion: v1
metadata:
  name: mydevops
  labels:
    app: mydevops
spec:
  ports:
    - port: 8080                               
      targetPort: 80                    
      nodePort: 31200
  selector:
    app: mydevops                    
  type: LoadBalancer                   
